# === DO_NOT_EDIT: pkg-ext site ===
site_name: model_lib
# === OK_EDIT: pkg-ext site ===

# === DO_NOT_EDIT: pkg-ext theme ===
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
# === OK_EDIT: pkg-ext theme ===

# === DO_NOT_EDIT: pkg-ext nav ===
nav:
  - Home: index.md
  - model_lib: _root/index.md
  - dump: dump/index.md
  - fields: fields/index.md
  - parse: parse/index.md
  - yaml: yaml/index.md
# === OK_EDIT: pkg-ext nav ===

# === DO_NOT_EDIT: pkg-ext extensions ===
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
# === OK_EDIT: pkg-ext extensions ===
